In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf

In [2]:
# creamos un escalar (tensor de 0 dimensiones#
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# comprobamos el numero de dimensiones con ndim
scalar.ndim

0

In [4]:
# creamos un vector (tensor de 1 dimension)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#creo un vector columnna
column_vector = tf.constant([[10], [10]])
column_vector

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [10]], dtype=int32)>

In [7]:
column_vector.ndim

2

In [8]:
#creamos una matriz (tensor de 2 dimensiones)
matriz = tf.constant([[10, 10], [10, 10]])
matriz

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [9]:
matriz.ndim

2

In [10]:
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
# creamos un tensor con tf.variable
tensor = tf.Variable([1, 2, 3])
tensor[1].assign(5)
tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 5, 3], dtype=int32)>

In [15]:
#creamos tensores pseuddoaletorios
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_1, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
# Creamos dos tensores aleatorios con semillas diferentes
random_3 = tf.random.Generator.from_seed(43)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(44)
random_4 = random_4.normal(shape=(3, 2))
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [17]:
#barajar un tensor , a considerar cuando queramos desordenar los datos
no_barajado = tf.constant([[10, 7], [3, 4], [2, 5]])
tf.random.shuffle(no_barajado)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
tf.random.shuffle(no_barajado, seed=42)
no_barajado

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
# creamos un tensor solo de unos
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [20]:
tf.ones_like(no_barajado)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [21]:
tf.ones_like(tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>

In [22]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [23]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A, shape=[2, 4, 3])
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [24]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
print("Tipo de dato de cada elemento:", rank_4_tensor.dtype)
print("Numero de dimensiones(rango)", rank_4_tensor.ndim)
print("Forma del tensor:", rank_4_tensor.shape)
print("Numero de elementos:", tf.size(rank_4_tensor).numpy())
print("Elementos en el primer eje del tensor", rank_4_tensor.shape[0])
print("Elememtos en el ultimo eje del tensor", rank_4_tensor.shape[-1])

Tipo de dato de cada elemento: <dtype: 'float32'>
Numero de dimensiones(rango) 4
Forma del tensor: (2, 3, 4, 5)
Numero de elementos: 120
Elementos en el primer eje del tensor 2
Elememtos en el ultimo eje del tensor 5


In [26]:
# obtenemos los dos primeros items de cada dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# obtenemos los dos primeros items de cada dimension excepto el ultimo
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
#creamos un tensor de rango2
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
#obtenemos el ultimo item de cada fila
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [29]:
# anhadimos una dimension extra (al final)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [30]:
#podemos hacer lo mismo usando tf.expand_dims
rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=-1)
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [31]:
#podemos anhadir valores a un tensor usando el operador +
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [32]:
#multiplicacion
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [33]:
#substraccion
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [34]:
# podemos usar una funcion de tensorflow equivalente a '*'
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [35]:
#multiplicacion de matrices
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
# tambien podemos usar el operador @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X_tr = tf.transpose(X)
X_tr @ Y


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [38]:
Y_tr = tf.transpose(Y)
Y_tr

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [39]:
X @ Y_tr

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [40]:
#funciones de agregacion:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([97, 75,  4, 51, 87, 21,  1, 62, 47, 24, 76, 57,  1, 83, 52, 51, 98,
       63, 18, 84, 39, 15, 45, 36, 50, 81,  5, 27, 93, 32, 94, 47, 89, 91,
       73, 66, 57, 47, 43, 50, 31, 89, 94, 15, 42, 73, 10,  2, 82, 71])>

In [41]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [42]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [43]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [44]:
tf.reduce_sum(E)


<tf.Tensor: shape=(), dtype=int64, numpy=2641>

In [46]:
# Ejercicio 1
# escalar:
scalar = tf.constant(7)
scalar.ndim, scalar.shape, scalar.dtype

(0, TensorShape([]), tf.int32)

In [48]:
vector = tf.constant([1, 2, 3])
vector.ndim, vector.shape, vector.dtype

(1, TensorShape([3]), tf.int32)

In [49]:
x_tr = tf.transpose(vector)
x_tr

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [50]:
x_tr.ndim, x_tr.shape, x_tr.dtype

(1, TensorShape([3]), tf.int32)

In [51]:
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [52]:
matrix.ndim, matrix.shape, matrix.dtype

(2, TensorShape([2, 2]), tf.int32)

In [54]:
X = tf.constant(np.random.random(size=(5, 300)))
X

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.13536844, 0.3251813 , 0.30680887, ..., 0.23538911, 0.34394678,
        0.77497302],
       [0.45988226, 0.89162732, 0.07780613, ..., 0.2019914 , 0.52710768,
        0.96459592],
       [0.66197675, 0.51192163, 0.88091483, ..., 0.53549375, 0.17616627,
        0.16455614],
       [0.80511752, 0.04958081, 0.77274455, ..., 0.60734318, 0.03829759,
        0.09672544],
       [0.13346895, 0.14838258, 0.44783085, ..., 0.26719711, 0.19925043,
        0.17988653]], shape=(5, 300))>

In [55]:
Y = tf.constant(np.random.random(size=(5, 300)))
Y

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.25704225, 0.32266753, 0.77700652, ..., 0.08145499, 0.93048771,
        0.14640043],
       [0.30423266, 0.51494731, 0.67697919, ..., 0.34042128, 0.56771864,
        0.86240546],
       [0.6678109 , 0.14984938, 0.11798152, ..., 0.00937148, 0.188403  ,
        0.94776975],
       [0.36789128, 0.66914331, 0.21171289, ..., 0.78351435, 0.63548632,
        0.46873803],
       [0.4836065 , 0.48383062, 0.35075406, ..., 0.78452946, 0.59601907,
        0.93378691]], shape=(5, 300))>

In [56]:
X_transpose = tf.transpose(X)
X_transpose

<tf.Tensor: shape=(300, 5), dtype=float64, numpy=
array([[0.13536844, 0.45988226, 0.66197675, 0.80511752, 0.13346895],
       [0.3251813 , 0.89162732, 0.51192163, 0.04958081, 0.14838258],
       [0.30680887, 0.07780613, 0.88091483, 0.77274455, 0.44783085],
       ...,
       [0.23538911, 0.2019914 , 0.53549375, 0.60734318, 0.26719711],
       [0.34394678, 0.52710768, 0.17616627, 0.03829759, 0.19925043],
       [0.77497302, 0.96459592, 0.16455614, 0.09672544, 0.17988653]],
      shape=(300, 5))>

In [57]:
X_transpose @ Y

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[0.97752407, 0.98300631, 0.71188245, ..., 0.90931529, 1.10295203,
        1.54584527],
       [0.78671346, 0.74574638, 0.97922112, ..., 0.49007179, 1.025165  ,
        1.46353291],
       [1.19167843, 1.00481899, 0.71567577, ..., 1.01652639, 1.2536052 ,
        1.72731516],
       ...,
       [0.83222041, 0.79588853, 0.60512407, ..., 0.77844026, 0.97980245,
        1.25037435],
       [0.47686613, 0.53084158, 0.72287018, ..., 0.39543033, 0.79557202,
        0.87590854],
       [0.72513351, 0.92319113, 1.35815899, ..., 0.60994857, 1.46840832,
        1.31460508]], shape=(300, 300))>

In [58]:
Y_transpose = tf.transpose(Y)
Y_transpose

<tf.Tensor: shape=(300, 5), dtype=float64, numpy=
array([[0.25704225, 0.30423266, 0.6678109 , 0.36789128, 0.4836065 ],
       [0.32266753, 0.51494731, 0.14984938, 0.66914331, 0.48383062],
       [0.77700652, 0.67697919, 0.11798152, 0.21171289, 0.35075406],
       ...,
       [0.08145499, 0.34042128, 0.00937148, 0.78351435, 0.78452946],
       [0.93048771, 0.56771864, 0.188403  , 0.63548632, 0.59601907],
       [0.14640043, 0.86240546, 0.94776975, 0.46873803, 0.93378691]],
      shape=(300, 5))>

In [59]:
X @ Y_transpose

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[71.65370655, 75.90865814, 71.10942364, 73.73860693, 74.03587245],
       [81.52997151, 83.46911589, 80.21904802, 80.5803784 , 83.46448709],
       [68.99629336, 75.07025671, 72.58186096, 74.68061958, 73.39303672],
       [75.6193016 , 80.22972732, 77.30818107, 78.66762833, 78.65018704],
       [75.03109178, 76.92002386, 75.06700324, 75.96631957, 74.07907767]])>

In [60]:
tensor = tf.constant(np.random.random(size=(1, 224, 224, 3)))
tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float64, numpy=
array([[[[0.18275441, 0.56893556, 0.65444026],
         [0.565149  , 0.67234955, 0.77964712],
         [0.61480014, 0.47180396, 0.12310436],
         ...,
         [0.45294618, 0.19018622, 0.44048992],
         [0.92811999, 0.38348205, 0.92052284],
         [0.68502075, 0.80185251, 0.49154168]],

        [[0.6226026 , 0.91518328, 0.07437362],
         [0.2506565 , 0.01293188, 0.8592351 ],
         [0.69414818, 0.17953527, 0.56632787],
         ...,
         [0.12115561, 0.92606349, 0.89600948],
         [0.98303308, 0.99924486, 0.03038135],
         [0.46423225, 0.5105573 , 0.51373668]],

        [[0.08584257, 0.24730672, 0.60485698],
         [0.20420747, 0.87710259, 0.04066405],
         [0.98506993, 0.30366317, 0.16333563],
         ...,
         [0.51077008, 0.4948258 , 0.06601106],
         [0.7484821 , 0.77832418, 0.23928295],
         [0.85515669, 0.49716235, 0.4763281 ]],

        ...,

        [[0.16712392, 0.9316545 , 

In [61]:
tensor.ndim, tensor.shape, tensor.dtype

(4, TensorShape([1, 224, 224, 3]), tf.float64)

In [62]:
tf.reduce_max(tensor), tf.reduce_min(tensor), tf.reduce_mean(tensor), tf.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.9999883672280534>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3.5758533887264576e-06>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.4994137571683702>,
 <tf.Tensor: shape=(), dtype=float64, numpy=75175.75403904043>)

In [63]:
tensor_sq = tf.squeeze(tensor)
tensor_sq

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.18275441, 0.56893556, 0.65444026],
        [0.565149  , 0.67234955, 0.77964712],
        [0.61480014, 0.47180396, 0.12310436],
        ...,
        [0.45294618, 0.19018622, 0.44048992],
        [0.92811999, 0.38348205, 0.92052284],
        [0.68502075, 0.80185251, 0.49154168]],

       [[0.6226026 , 0.91518328, 0.07437362],
        [0.2506565 , 0.01293188, 0.8592351 ],
        [0.69414818, 0.17953527, 0.56632787],
        ...,
        [0.12115561, 0.92606349, 0.89600948],
        [0.98303308, 0.99924486, 0.03038135],
        [0.46423225, 0.5105573 , 0.51373668]],

       [[0.08584257, 0.24730672, 0.60485698],
        [0.20420747, 0.87710259, 0.04066405],
        [0.98506993, 0.30366317, 0.16333563],
        ...,
        [0.51077008, 0.4948258 , 0.06601106],
        [0.7484821 , 0.77832418, 0.23928295],
        [0.85515669, 0.49716235, 0.4763281 ]],

       ...,

       [[0.16712392, 0.9316545 , 0.85092856],
        [0.44